
abstract=
ontologyTitle=GUIA ontology
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=https://guia.org/
ontologyName=GUIA Ontology
thisVersionURI=null
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=0.1.0
licenseURI=http://purl.org/NET/rdflicense/cc-by4.0
licenseName=http://purl.org/NET/rdflicense/cc-by4.0
licenseIconURL=null
citeAs=Andrea Cimmino Arriaga, Covadonga Arias. GUIA ontology. Revision: 0.1.0.
DOI=
status=Ontology Specification Draft
logo=
description=This ontology defines concepts to represent academic course guides in higher education. It models degrees, courses, teaching roles, learning design, resources, schedules, and evaluation systems, while reusing existing vocabularies such as Schema.org whenever possible.
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Andrea Cimmino Arriaga;Covadonga Arias
authorsURI=;
authorsInstitution=;
authorsInstitutionURI=;
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
